const words: string[] = [
  "LEÓN",
  "TIGRE",
  "ELEFANTE",
  "JIRAFA",
  "RINOCERONTE",
  "HIPOPÓTAMO",
  "OSO POLAR",
  "OSO PARDO",
  "LOBO",
  "ZORRO",
  "PERRO",
  "GATO",
  "DELFÍN",
  "BALLENA AZUL",
  "ORCA",
  "FOCA",
  "PINGÜINO",
  "ÁGUILA",
  "BÚHO",
  "HALCÓN",
  "COLIBRÍ",
  "LORO",
  "PAVO REAL",
  "COCODRILO",
  "CAIMÁN",
  "SERPIENTE",
  "TORTUGA",
  "CAMALEÓN",
  "RANA",
  "SAPO",
  "TIBURÓN",
  "PEZ PAYASO",
  "CABALLITO DE MAR",
  "PULPO",
  "CALAMAR",
  "CANGREJO",
  "LANGOSTA",
  "ABEJA",
  "MARIPOSA",
  "MOSCA",
  "HORMIGA",
  "ARAÑA",
  "ESCORPIÓN",
  "MURCIÉLAGO",
  "CEBRA",
  "CAMELLO",
  "CANGURO",
  "KOALA",
  "ARMADILLO",
  "ERIZO",
];
export function getRandomWord(): string {
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
}
